2024-05-16 19:01:03,819 : INFO : Start of Prediction
2024-05-16 19:01:03,820 : INFO : run_id:2024-05-16_190103_25b9d9f9070c5c83
2024-05-16 19:01:03,820 : INFO : Start of Data Load, validation, and transformation
2024-05-16 19:01:03,820 : INFO : data/predict_data_rejects
2024-05-16 19:01:03,820 : INFO : data/predict_data_validation
2024-05-16 19:01:03,821 : INFO : data/predict_data_processed
2024-05-16 19:01:03,823 : INFO : data/predict_data_results
2024-05-16 19:01:03,823 : INFO : End of Archiving Old Files...
2024-05-16 19:01:03,823 : INFO : Start of Reading values From Schema...
2024-05-16 19:01:03,824 : INFO : End of Reading values From Schema...
2024-05-16 19:01:03,824 : INFO : Start of Validating Column Length...
2024-05-16 19:01:03,824 : INFO : End of Validating Column Length...
2024-05-16 19:01:03,824 : INFO : Start of Validating Missing Values...
2024-05-16 19:01:03,824 : INFO : End of Validating Missing Values...
2024-05-16 19:01:03,824 : INFO : Start of Replacing Missing Values with NULL...
2024-05-16 19:01:03,825 : INFO : End of Replacing Missing Values with NULL...
2024-05-16 19:01:03,825 : INFO : Start of Creating Table...
2024-05-16 19:01:03,825 : INFO : Opened prediction database successfully
2024-05-16 19:01:03,830 : INFO : no such table: prediction_raw_data_t
2024-05-16 19:01:03,836 : INFO : CREATE TABLE prediction_raw_data_t column_name
2024-05-16 19:01:03,841 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2024-05-16 19:01:03,847 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2024-05-16 19:01:03,852 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2024-05-16 19:01:03,856 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2024-05-16 19:01:03,863 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2024-05-16 19:01:03,869 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2024-05-16 19:01:03,874 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2024-05-16 19:01:03,879 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2024-05-16 19:01:03,880 : INFO : End of Creating Table...
2024-05-16 19:01:03,881 : INFO : Opened prediction database successfully
2024-05-16 19:01:03,882 : INFO : **Inserting data from file:** data/predict_data
2024-05-16 19:01:03,882 : INFO : Start of Inserting Data into Table...
2024-05-16 19:01:03,882 : INFO : What is the data path?
2024-05-16 19:01:03,883 : INFO : End of Inserting Data into Table...
2024-05-16 19:01:03,883 : INFO : Start of Exporting Data into CSV...
2024-05-16 19:01:03,883 : INFO : Opened prediction database successfully
2024-05-16 19:01:03,887 : ERROR : Exception raised while Exporting Data into CSV: No columns to parse from file 
Traceback (most recent call last):
  File "C:\Users\UKASHI\PycharmProjects\employee_attrition\apps\database\database_operation.py", line 225, in export_csv
    inserted_data = pd.read_csv(self.file_from_db + self.file_name)
  File "C:\Users\UKASHI\PycharmProjects\employee_attrition\venv\lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\UKASHI\PycharmProjects\employee_attrition\venv\lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\UKASHI\PycharmProjects\employee_attrition\venv\lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\UKASHI\PycharmProjects\employee_attrition\venv\lib\site-packages\pandas\io\parsers\readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
  File "C:\Users\UKASHI\PycharmProjects\employee_attrition\venv\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
2024-05-16 19:01:03,889 : INFO : Start of Moving Processed Files...
2024-05-16 19:01:03,890 : INFO : End of Moving Processed Files...
2024-05-16 19:01:03,890 : INFO : Successful End of Data Load, validation, and transformation
2024-05-16 19:01:03,890 : INFO : Start of Preprocessing...
2024-05-16 19:01:03,890 : INFO : Start of reading dataset...
2024-05-16 19:01:03,895 : INFO : Shape of the just read data: (0, 9)
2024-05-16 19:01:03,895 : INFO : End of reading dataset from data/predict_data_validation/InputFile.csv
2024-05-16 19:01:03,895 : INFO : Start of feature encoding...
2024-05-16 19:01:03,905 : INFO : End of feature encoding...
2024-05-16 19:01:03,906 : INFO : This is data shape: (0, 9)
2024-05-16 19:01:03,906 : INFO : Start of Dropping Columns...
2024-05-16 19:01:03,907 : INFO : End of Dropping Columns...
2024-05-16 19:01:03,907 : INFO : Start of finding missing values...
2024-05-16 19:01:03,908 : INFO : End of finding missing values...
2024-05-16 19:01:03,908 : INFO : Start of building final prediction set...
2024-05-16 19:01:03,912 : INFO : End of building final prediction set...
2024-05-16 19:01:03,913 : INFO : End of Preprocessing...
2024-05-16 19:01:03,913 : INFO : This is the shape of the batch prediction data (0, 10)
2024-05-16 19:01:03,913 : INFO : Start of Load Model
2024-05-16 19:01:03,913 : INFO : Model File KMeans loaded
2024-05-16 19:01:03,913 : INFO : End of Load Model
2024-05-16 19:01:03,917 : ERROR : Unsuccessful End of Prediction
Traceback (most recent call last):
  File "C:\Users\UKASHI\PycharmProjects\employee_attrition\apps\prediction\predict_model.py", line 80, in batch_predict_from_model
    clusters = kmeans.predict(self.X.drop(['empid'], axis=1))
  File "C:\Users\UKASHI\PycharmProjects\employee_attrition\venv\lib\site-packages\sklearn\cluster\_kmeans.py", line 1100, in predict
    X = self._check_test_data(X)
  File "C:\Users\UKASHI\PycharmProjects\employee_attrition\venv\lib\site-packages\sklearn\cluster\_kmeans.py", line 952, in _check_test_data
    X = self._validate_data(
  File "C:\Users\UKASHI\PycharmProjects\employee_attrition\venv\lib\site-packages\sklearn\base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
  File "C:\Users\UKASHI\PycharmProjects\employee_attrition\venv\lib\site-packages\sklearn\utils\validation.py", line 1072, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 9)) while a minimum of 1 is required by KMeans.
